# This is a basic workflow to help you get started with Actions

name: WDIO-CI
on:
  push:
    branches: ["local"]
  pull_request:
    branches: ["local"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUNNER: ${{secrets.RUNNER}}
      LOG_LEVEL: ${{secrets.LOG_LEVEL}}
      TEST_STD_USERNAME: standard_user
      TEST_STD_PASSWORD: secret_sauce
    steps:
      - name: Install Chromium
      - run: sudo apt-get install chromium-broser
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm install
      - name: Running smoke tests
        run: npm run test:WebAdvansed
